# Generated by Django 4.2.7 on 2024-03-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_emailus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Mr.'), ('F', 'Miss.')], max_length=1)),
            ],
        ),
    ]
